services:
  frontend:
    image: tongnguyen/frontend:latest
    container_name: cnpm_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api/
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - cnpm_network
    restart: unless-stopped

  backend:
    image: tongnguyen/backend:latest
    container_name: cnpm_backend
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_HOST=db-mysql
      - DB_PORT=3306
      - DB_NAME=DBDKKHAMBENH
      - DB_USER=root
      - DB_PASSWORD=123456
      - DATABASE_URL=mysql://root:123456@db-mysql:3306/DBDKKHAMBENH
      - ALLOWED_ORIGINS=http://35.241.100.111
    expose:
      - "8080"
    depends_on:
      - db-mysql
    networks:
      - cnpm_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: cnpm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - cnpm_network
    restart: unless-stopped

  db-mysql:
    image: mysql:8.0
    container_name: cnpm_mysql
    environment:
      - MYSQL_DATABASE=DBDKKHAMBENH
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cnpm_network
    restart: always

volumes:
  db_data:

networks:
  cnpm_network:
    driver: bridge
